Feature: partyroom participatn tab -> grade tab -> user grade callaps list
pfplay/pfplay-web pull request #156
Opened 2024-08-11 11:11 UTC by YoonJongok

### Summary

Participant tab의 유저 grade 탭의 유저 grade 리스트 PR입니다.

<img width="384" alt="2024-08-11_13-08-21" src="https://github.com/user-attachments/assets/c611e230-e9ed-43ae-bace-e16e5dbffb0a">

### Todo

- 해당 유저의 grade에 따라 다른 유저의 메뉴 옵션을 눌렀을 때 렌더되는menu option 패널의 리스트가 적용되어야 합니다.

N/A

### Issue

N/A

### Reference

N/A

2024-08-11 11:17 UTC, bear-bear-bear commented
<img width="241" alt="스크린샷 2024-08-11 오후 8 16 56" src="https://github.com/user-attachments/assets/0fb5b05e-945f-4b8d-a282-8ba88ae31587">
<img width="182" alt="스크린샷 2024-08-11 오후 8 17 01" src="https://github.com/user-attachments/assets/03a0c499-9ebc-410e-9238-927e7fe756c0">

크아악

2024-08-11 16:57 UTC, bear-bear-bear requested changes
고생하셨스무니당 👍👍

2024-08-11 16:57 UTC, bear-bear-bear commented on src/shared/ui/components/user-list-item/index.ts
> +} from './ui/user-list-item-suffix.component';
이미 아실 수 있지만 말씀드리면, shared 레이어는 이미 그 자체로 슬라이스기 때문에 세그먼트 하위 구조는 자유입니다. 즉 내부에서 또 슬라이스의 구조를 띌 필요가 없습니다. 하지만 말 그대로 자유기에, 틀린 것은 아님다

2024-08-11 16:57 UTC, bear-bear-bear commented on src/shared/ui/components/user-list-item/ui/user-list-item-suffix.component.tsx
> +  type: SuffixType;
[의견]
`type: SuffixType;` 이 라인은 지워지는게 맞을 듯 합니다.

2024-08-11 16:57 UTC, bear-bear-bear commented on src/shared/lib/functions/categorize.ts
> +};
[의견]
K가 제네릭일 이유가 없는 듯 합니다.

```tsx
type CategorizeParams<T> = {
  items: T[];
  categoryKey: keyof T;
  getCategoryValue: (item: T) => string;
  orderReferenceArr?: string[];
};
```

2024-08-11 16:57 UTC, bear-bear-bear commented on src/shared/lib/functions/categorize.ts
> +export const categorize = <T, K extends keyof T>({
테스트 작성 부탁드림다

2024-08-11 16:57 UTC, bear-bear-bear commented on src/shared/api/http/types/partyroom.ts
> +}
[변경 요청]
`partyrooms/*` 라우트들이 모여있는 partyrooms.ts가 이미 있습니다. 이 파일 제거하고 해당 파일로 이동 부탁드려요

2024-08-11 16:57 UTC, bear-bear-bear commented on src/app/parties/(room)/[id]/page.tsx
> +            <TabList className={cn('w-full flexRow')}>
[변경 요청]
flex-1 flexCol 은 탭 패널로 flex-grow를 전파하기 위함입니다. 다시 추가해주세용

<img width="300" src="https://github.com/user-attachments/assets/8c30e451-30f3-4fe6-aad2-fb5a926d5363" />

2024-08-11 16:57 UTC, bear-bear-bear commented on src/features/playlist/list/ui/collapsable-list.component.tsx
> +export default CollapsibleList;
[질문]
삭제되면 될까요? 사용부가 없네요

2024-08-11 16:57 UTC, bear-bear-bear commented on src/widgets/partyroom-participant-panel/model/render-suffix.tsx
> +import { SuffixType } from '@/shared/ui/components/user-list-item/model/user-list-item.model';
[변경 요청]
``` tsx
import { SuffixType } from '@/shared/ui/components/user-list-item/model/user-list-item.model';
```
barrel file 통해 import 하도록 변경해주세용

2024-08-11 16:57 UTC, bear-bear-bear commented on src/widgets/partyroom-participant-panel/model/render-suffix.tsx
> +};
[의견]
뷰모델이라면 뷰모델이지만, 사용부 컴포넌트 내로 옮겨도 깔끔하고 괜찮을 듯 한데 어떠실까요?

``` tsx
const UserGradePanel = () => {
   // ...
  return (
    <div className='flex flex-col gap-6'>
      {Object.entries(categorizedParticipants).map(([category, participants]) => {
        return (
          <CollapseList key={category} title={category} displaySuffix={false}>
            {participants.map((participant) => {
              const suffix = (() => {
                if (djing) {
                   return <UserListItemSuffix type='tag' value={t.~~} />;
                }
                if (me) {
                   return <UserListItemSuffix type='tag' value={t.~~} />;
                }
              })();
              
              return (
                <UserListItem
                  // ...
                  suffix={suffix && { type: 'tag', Component: suffix }}
                />
              );
            })}
          </CollapseList>
        );
      })}
    </div>
  );
};

2024-08-11 16:57 UTC, bear-bear-bear commented on src/widgets/partyroom-participant-panel/ui/parts/user-grade-panel.component.tsx
> +  const [currentDj] = djingQueue?.djs.slice().sort((a, b) => a.orderNumber - b.orderNumber) ?? [];
[변경 요청]
useCurrentPartyroom에 currentDj가 추가되었습니다. 해당 필드 사용하도록 교체 부탁드려요~

2024-08-11 16:57 UTC, bear-bear-bear commented on src/widgets/partyroom-participant-panel/model/user-grade-panel.model.tsx
> +  }
[의견]
isMe와 isDjing이라는 상태를 계산하여 assign 하는게 'categorize' 라는 모듈의 관심사인가? 생각했을 때 조금 갸우뚱하게 됩니다. suffix 렌더를 위한 assign이라면 컴포넌트 내에서 인라인으로 계산하는건 어떨까요?

```tsx
const { me, currentDj } = useCurrentPartyroom();

// ...

<CollapseList key={category} title={category} displaySuffix={false}>
  {participants.map((participant) => {
     const isDj = participant.memberId = currentDj.memberId;
     const isMe = participant.memberId = me.memberId;
     // ...
```

2024-08-11 16:57 UTC, bear-bear-bear commented on src/widgets/partyroom-participant-panel/ui/partyroom-participant-panel.component.tsx
> +'use client';
[질문]
use client 가 필요한 컴포넌트가 맞을까요?

2024-08-12 12:51 UTC, bear-bear-bear commented on src/app/parties/(room)/[id]/page.tsx
> +            <TabList className={cn('w-full flexRow')}>
아하. headless ui 버전 업 이후 TabGroup이 단순 Context가 아니라 div가 된 것도 깨진 이유 중 하나네요. TabGroup도 아래처럼 스타일 추가 부탁드림다

<img width="578" alt="image" src="https://github.com/user-attachments/assets/c48026ae-741e-4ea4-92ed-b5191e1b9a0d">

2024-08-15 08:11 UTC, YoonJongok commented on src/app/parties/(room)/[id]/page.tsx
> +            <TabList className={cn('w-full flexRow')}>
넵 적용하겠습니다 :)

2024-08-15 08:12 UTC, YoonJongok commented on src/features/playlist/list/ui/collapsable-list.component.tsx
> +export default CollapsibleList;
넵

2024-08-15 08:18 UTC, YoonJongok commented on src/shared/lib/functions/categorize.ts
> +export const categorize = <T, K extends keyof T>({
넵!

2024-08-15 08:22 UTC, YoonJongok commented on src/shared/ui/components/user-list-item/index.ts
> +} from './ui/user-list-item-suffix.component';
넵 다시 한 번 짚어주셔서 감사합니다! :)

2024-08-15 08:26 UTC, YoonJongok commented on src/widgets/partyroom-participant-panel/ui/parts/user-grade-panel.component.tsx
> +  const [currentDj] = djingQueue?.djs.slice().sort((a, b) => a.orderNumber - b.orderNumber) ?? [];
넵!

2024-08-15 08:27 UTC, YoonJongok commented on src/widgets/partyroom-participant-panel/ui/partyroom-participant-panel.component.tsx
> +'use client';
좋은 디테일입니다! 감사합니다!

2024-08-17 19:46 UTC, bear-bear-bear approved these changes

2024-08-17 19:47 UTC, merged