refactor: 파티룸 소켓 클라이언트 추상화, 사용부 구조 개선
pfplay/pfplay-web pull request #161
Opened 2024-08-26 17:24 UTC by bear-bear-bear

### Summary

#### 작업 배경
채팅 작업을 하려는데 어디서부터 시작해야 할지 헷갈렸습니다.

> destination은 어디에 추가해야 하지? 핸들러는 어디에 추가해야 하지? 기존 구조를 따르자니 app 레이어에 너무 많은 로직이 들어가는데 이건 심한 코드스멜 아닐까?

위와 같은 고민이 들어, 먼저 기존 소켓 클라이언트 관련 항목들을 개선합니다.

#### AS-IS
* app 레이어에서 "정책" 로직을 들고 있습니다.
* entities 레이어의 partyroom-client 슬라이스는 shared의 SocketClient를 provider로 그대로 바이패스하는 단순한 역할을 합니다. 해당 슬라이스 사용자는 SocketClient의 어떤 메서드를 사용해야 원하는 기능을 구현할 수 있을지 헷갈립니다.
* entities 레이어의 current-partyroom 슬라이스는 최초에는 "현재 파티룸에 대한 스토어"만을 가지고 있었지만, 점점 살이 붙어 "파티룸 구독에 대한 이벤트 핸들러", "파티룸 구독에 대한 destination들", "파티룸 구독 정책 관련 함수", "파티룸 초기화 정보 fetch 함수" 등을 무분별하게 내보내는 모듈이 됐습니다.

#### TO-BE
* app 레이어는 하위 레이어에서 제공하는 "feature"들에 대해 "페이지에 연결"하는 정도의 최소한의 로직만을 들고 있습니다.
* entities 레이어의 partyroom-client 슬라이스는 shared의 SocketClient를 캡슐화하여 도메인과 관련된 최소한의 인터페이스만을 노출하며, partyroom 구독에 대한 정책을 포함합니다.이전에 current-partyroom 슬라이스가 가지고 있던 파티룸 구독에 대한 항목들은 이제 이 슬라이스가 가져갑니다.
* entities 레이어의 current-partyroom 슬라이스는 이제 "현재 파티룸에 대한 스토어"만을 가집니다.

2024-08-27 09:44 UTC, YoonJongok commented on src/shared/api/websocket/client.ts
> +    const DESTINATION = {
[의견]
startHeartbeat이 자주 호출되는 함수는 아닐 것 같지만, DESTINATION 상수는 클래스 밖으로 빼서 메모리에 한 번만 할당되게 하는 것은 어떨까요?

2024-08-27 10:30 UTC, YoonJongok requested changes
고생하셨습니다. 코멘트 하나만 답변 부탁드립니다 :)

2024-08-27 15:46 UTC, bear-bear-bear commented on src/shared/api/websocket/client.ts
> +    const DESTINATION = {
현재 위 메서드가 속한 클래스는 앱 내에서 단 한 곳에서 한 번만 instantiation 되며, 앱 초기화 시점에 단 한 번 실행됩니다. 그리고 곧 없어질 메서드입니다 (주석에 적힌대로). 성능 변화가 크지 않아 없어지기 전까진 그대로 둬도 괜찮을 것 같습니다.
생각 못 한 부분인데 다음에 비슷한 케이스가 나오면 신경쓸 수 있겠네요 감사합니다 ~

2024-08-28 11:18 UTC, YoonJongok approved these changes

2024-08-28 11:25 UTC, merged