feat: dialog를 현재 리액트 렌더 컨텍스트 밖에서 띄우는 기능 개발
pfplay/pfplay-web pull request #219
Opened 2024-11-02 12:49 UTC by bear-bear-bear

### Summary

> 이 파일 내에서 useDialog를 사용하려면 app/logout.tsx 내 provider의 위게를 변경하여 QueryClientProvider를 DialogProvider 내부로 이동해야 하는데, 이러면 다이얼로그 body 내에서 react-query를 사용할 수 없음 (Error: No QueryClient set, use QueryClientProvider to set one). dialog를 provider가 아닌 다른 방식으로 제공하는걸 검토해봐야 할 듯

위 문제 해결을 위해 dialog를 리액트 렌더 컨텍스트 밖에서 띄우는 기능을 개발하고, 이를 react-query 전역 에러 핸들러에 연결합니다.

<img width="469" alt="스크린샷 2024-11-02 오후 9 46 51" src="https://github.com/user-attachments/assets/c03afa45-58ec-44bb-9b9f-82f144a357b2">

2024-11-16 15:35 UTC, Ellsy23 commented
good

2024-11-19 10:57 UTC, YoonJongok commented on src/app/_providers/react-query.provider.tsx
> +  const { destroy } = Dialog.open({
[질문]
질문이 있습니다. 현재 구현부를 봤을 때 순환 참조 문제가 야기 될 수도 있을 것 같습니다.
코드의 실행 순서를 보면 
1. Dialog.open()이 호출됨
2. open 함수가 destroy 함수를 생성
3. 그런데 destroy 함수를 사용하는 Body와 onClose가 open 함수의 인자로 전달됨
즉, 아직 생성되지 않은 destroy 함수를 참조하는 코드가 먼저 전달되는 형태로 보입니다. 
다른 제안 드릴 만한 옵션은 아직 없습니다. 준재님 의견이 궁금합니다.

2024-11-19 11:04 UTC, YoonJongok requested changes
질문 하나 드렸습니다! 의견 부탁드립니다 :)

2024-11-19 11:14 UTC, bear-bear-bear commented on src/app/_providers/react-query.provider.tsx
> +  const { destroy } = Dialog.open({
@YoonJongok 

함수 내부 평가는 실행 시점에 이뤄지기에 문제는 없습니다.

<img width="903" alt="image" src="https://github.com/user-attachments/assets/3c8db5e4-f45d-4a3c-a716-8f443ce1e60b">

그럼에도 헷갈리는 코드긴 해서 차선책을 생각해보자면 onClose prop은 단순 리스너로 취급하고 내부에서 destroy를 삽입해주고, Body의 인자로 destroy를 넘겨주는 방법이 있는데요, (Dialog.open 함수의 return 값은 없애기)

처음엔 위처럼 했다가 암시적이고 오히려 더 지저분한 느낌이 들어 지금 형태로 전환했습니다.

2024-11-19 12:12 UTC, YoonJongok approved these changes

2024-11-19 12:13 UTC, merged